/*
NAME: EECS 447: Data Population
DESCRIPTION: Insertion of data into the DATABASE SYSTEM FOR LIBRARY MANAGEMENT
CONTRIBUTORS: JAIDEN GREEN, SHERO BAIG, LUIS, ERIC, AMRIT
START DATE: OCTOBER 29, 2025
LAST UPDATED: OCTOBER 29, 2025
*/
